export const INCREMENT = 'INCREMENT';
export const DECREMENT = 'DECREMENT';

export const ADD_CONTESTANT = 'ADD_CONTESTANT';
export const REMOVE_CONTESTANT = 'REMOVE_CONTESTANT';
export const CHANGE_CONTESTANT = 'CHANGE_CONTESTANT';

export const LOAD_CONTESTANTS = 'LOAD_CONTESTANTS';
export const LOAD_ACTIVITIES = 'LOAD_ACTIVITIES';